### ISSUE TITLE
My Raspberry Pi losing Chromecast links/names/sinks

### ISSUE THREAD

**Issue by nachochip** [BaReinhard/Multiroom-Audio-iOS#12]
So, I've noticed an issue on a daily - every other day basis.  What happens is that we get to a point in the day that we want to cast to the Raspberry Pi, some days it will work, some it will not.  Sometimes, I can use 'changesink' command, it will list the chromecast sinks availabel, and I can pick the one desired.  But sometimes this doesn't work.  I have tracked it down to an issue with the detection of the Chromecast Names. 

For example: 
- I run 'pactl list short sinks'
- It provides:
1	bedroom_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
2	home_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
3	kitchen_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
4	bathroom_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
5	tv_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED

I always, always use home_chromecast.

Then another day, or another time of day, when we decide we want to cast again to the setup, it doesn't work, and I come to the Raspberry Pi and I run the same command and it provides:
1	bedroom_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
2	bedroom_chromecast.2	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
3	bedroom_chromecast.3	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
4	home_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
5	home_chromecast.2	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
6	home_chromecast.3	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
7	kitchen_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
8	kitchen_chromecast.2	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
9	kitchen_chromecast.3	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
10	bathroom_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
11	bathroom_chromecast.2	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
12	bathroom_chromecast.3	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
13	tv_chromecast	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
14	tv_chromecast.2	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
15	tv_chromecast.3	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED

I have figured out that sometimes I can select the 'home_chromecast' with no extension and it will work, and sometimes it will not work.

What is odd, is that when it is not working, I see the list mentioned above (2nd list), I decide to reboot the Raspberry Pi, and re-run the same command I just ran, and it will give me a diferent list, (usually the more shorter list I mentioned above first).  I use changesink and select the 'home_chromecast' and it works this time. 

- Have you found this issue? (It seems to occur sporadically, as if the chromecasts rename themselves?)
- Using a standard Android or iOs device looking at the Chromecast options to cast, I never see doubles or triples.  But yet the Raspberry Pi software is observing multiples.

- My desire is to simply have the Raspberry Pi consistent and not 'lost connection'

**Comment by BaReinhard** [comment]
This isn't something I've ever seen before. I'm guessing this may be an issue with the pulseaudio-dlna application. I will look into this issue on their github repo. I'm guessing  that the best solution for the time being would be running a cron job ever few hours to check to see if music is playing to the pi and check if there isnt a list of duped and if not have it reboot. It's a bit Mickey Mouse but for the time being I would imagine it would fix the issues. I'd have to research this further but it could also be an issue with pulseaudio itself.

Do you use the web interface at all or simply use the cli?

**Comment by nachochip** [comment]
I only use CLI for now.



On Jul 1, 2017 12:49 AM, "Brett Reinhard" <notifications@github.com> wrote:

This isn't something I've ever seen before. I'm guessing this may be an
issue with the pulseaudio-dlna application. I will look into this issue on
their github repo. I'm guessing that the best solution for the time being
would be running a cron job ever few hours to check to see if music is
playing to the pi and check if there isnt a list of duped and if not have
it reboot. It's a bit Mickey Mouse but for the time being I would imagine
it would fix the issues. I'd have to research this further but it could
also be an issue with pulseaudio itself.

Do you use the web interface at all or simply use the cli?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BaReinhard/Multiroom-Audio-iOS/issues/12#issuecomment-312412748>,
or mute the thread

**Comment by nachochip** [comment]
Closing for now.  I haven't found a solution.
