### ISSUE TITLE
iOS notifications causing MultiRoom Controller to change to default

### ISSUE THREAD

**Issue by fatfinger** [BaReinhard/Multiroom-Audio-iOS#17]
Is it possible to configure the MultiRoom Controller to autorefresh and default to a location other than 0ANALOGSTEREO?

**Comment by BaReinhard** [comment]
It is possible, but will require some refactoring of code. Unfortunately, this angular app could use a good amount of code refactoring to really clean up the code base and make this far simpler to understand. Forgive my naive self back when I first wrote this I had just started writing javascript about a month or 2 before.

Unfortunately, I don't have much free time between work/school/home life. That being said I have been thinking of doing at least a refactoring of for (at the very least) the front end and server js files. Possibly a rewrite in react would be a better option to keep the code relevant. 

if time permits I will use Vue and open an issue to get other end user feedback for what they would like implemented. However, this may just be a pipe dream as I don't see any over abundance of free time in the coming future.


I strongly encourage you take a stab at the front end code and see if you can mock something up to make this work, if you do and create a pull request ill do a code review and look to merging with the master branch.
