### ISSUE TITLE
pulseaudio-dlna stuckn running as root

### ISSUE THREAD

**Issue by dony71** [BaReinhard/Multiroom-Audio-iOS#7]
pulseaudio-dlna run in rc.local as root
i notice it cannot get it working
this issue is exactly reported in https://github.com/masmu/pulseaudio-dlna/issues/137
it said fix in ver.0.4.7 but your installation package is already using ver.0.5.2

**Comment by BaReinhard** [comment]
pulseaudio-dlna needs to be run as root user

I'm not sure what your issue is, do you have any error messages? How are you running pulseaudio-dlna?

**Comment by dony71** [comment]
yes, i run pulseaudio-dlna as root and it stucks in console like below
--------------------------------------------------------------------------------
root@RetrOrangePi:~# pulseaudio-dlna
04-01 01:27:03 pulseaudio_dlna.__main__                       INFO     Running as root. Starting daemon ...
04-01 01:27:03 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...


however if run pulseaudio-dlna as non-root, it goes further, but got permission denied which is understandable due to dbus cannot be loaded as non-root
----------------------------------------------------------------------
pi@RetrOrangePi:~$ pulseaudio-dlna
04-01 01:28:14 pulseaudio_dlna.notification                   ERROR    notify2 could not be initialized! Notifications will most likely not work.
04-01 01:28:14 pulseaudio_dlna.application                    INFO     Using version: 0.5.2
04-01 01:28:14 pulseaudio_dlna.application                    INFO     Using localhost: 128.168.1.40:8080
04-01 01:28:14 pulseaudio_dlna.application                    INFO     Encoder settings:
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="True" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
04-01 01:28:14 pulseaudio_dlna.application                    INFO     Codec settings:
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac" backend="generic">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16" backend="generic">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus" backend="generic">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="generic">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac" backend="generic">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav" backend="generic">
04-01 01:28:14 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg" backend="generic">
04-01 01:28:14 pulseaudio_dlna.streamserver                   CRITICAL The streaming server could not bind to your specified port (8080). Perhaps this is already in use? The application cannot work properly!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/__init__.py", line 48, in discover
    mdns.run(ttl)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/mdns.py", line 54, in run
    self.zeroconf = zeroconf.Zeroconf()
  File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 1336, in __init__
    self._listen_socket = new_socket()
  File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 1303, in new_socket
    s.setsockopt(socket.SOL_SOCKET, reuseport, 1)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 92] Protocol not available
Failed to create secure directory (/run/user/0/pulse): Permission denied
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
04-01 01:28:14 pulseaudio_dlna.pulseaudio                     CRITICAL PulseAudio seems not to be running or PulseAudio dbus module could not be loaded. The application cannot work properly!

**Comment by BaReinhard** [comment]
What happens when you run it as sudo

`sudo pulseaudio-dlna&`

**Comment by BaReinhard** [comment]
I guess I should ask, do you have any chromecast devices on your network?

**Comment by BaReinhard** [comment]
I recently ran into the same issue, it looks as though a current bug in pulseaudio-dlna has surfaced. I am unsure what changed, whether it was dlna or pulseaudio, but something is a miss.
I will be sure to get to the bottom of this, as it's essential to the project.

**Comment by dony71** [comment]
same problem executing sudo pulseaudio-dlna&

**Comment by dony71** [comment]
@BaReinhard : what is actually server.js doing? is it executing any script like changesink when choosing certain sink icon on Web UI multiroom controller?

**Comment by BaReinhard** [comment]
there turns out to be an issue with pulseaudio-dlna, you should be able to run 

```
sudo apt-get remove pulseaudio-dlna

sudo apt-get install pulseaudio-dlna
```
the debian sources have just been updated as of today.


server.js handles a few things, among them is a child_process a shell script which takes a parameter and changes the output sink to the supplied parameter. The reason for server.js is that is used as a connection between the Web UI and the underlying operating system.

**Comment by dony71** [comment]
yeah ... i get it working on the pulseaudio-dlna
however i cannot change sink using server.js
btw i'm using banana pi instead, but i think it should work also since banana pi same armv7 like RPi
can you tell me more details which shell script server.js calls?
i'm wondering maybe i'm missing some shell script?

**Comment by BaReinhard** [comment]
It is possible you are missing a shell script, but unlikely unless you have changed something.

In server.js there is an exec process that calls `"/usr/local/bin/changesink" +index`. This is essentially passing the param `index` to changesink. You should have a shell script called `changesink` in your `/usr/local/bin` directory. 

If that checks out would you mind sending me the contents of your server.js 


If you can go into your terminal and run `restart_web_ui` then open a web browser and open the web UI. When you click a button, you should see a number (the number of the sink) output to the console. This shows that the Web UI is working and communicating properly with node.

You should ensure that nodejs is always run as user, if its run as root it won't have access to the input stream.

**Comment by dony71** [comment]
I didn't change content of server.js, so it's exactly like yours
While web UI is running, I can see in terminal sink index# changing according to sink icon I choose
However index won't change, always shows sink index# 3 which default sink index
------------------------------------------------------------------------------------
pulse@RetrOrangePi:~$ pactl list short sink-inputs
0       3       -       module-equalizer-sink.c float32le 2ch 44100Hz

**Comment by BaReinhard** [comment]
what shows up with `pactl list short sinks`?

**Comment by BaReinhard** [comment]
I would also make sure that changeSinks is executable

**Comment by dony71** [comment]
yeap ... i forgot to chmod +x changesinks
it works now .....  thank you for your support
now waiting for volume to be implemented :)

**Comment by BaReinhard** [comment]
Glad it's working. Yeah was messing with it last night but got tired and went to bed that's the next thing to be fixed.

**Comment by BaReinhard** [comment]
@dony71

I know it's been a while but I have fixed the volume control and it will update to the specific sinks volume. Everything as of now works. I will eventually get to some better styling but for now it shall suffice.
