### ISSUE TITLE
Problem when installing ( 'usr/local/bin/enable_web_startup': No such file or directory)

### ISSUE THREAD

**Issue by nachochip** [BaReinhard/Multiroom-Audio-iOS#8]
I am getting two errors that I see at the end of the install.  I am using Raspberry Pi 2, Ubuntu armhf base.  The two errors are:
cp: cannot stat 'usr/local/bin/enable_web_startup': No such file or directory
chmod: cannot access '/usr/local/bin/enable_web_startup': No such file or directory

I see these error just before it finishes installing.  I also see it after the final questions.  See my 2 excerpts.  This is not allowing me to continue on to the setting the sinks and the web page only has the Volume at the top of the page. I appreciate your help.

1) 
 ======================================================================
 ====================== Installing Node JS ============================
==================> Executing: ./node_install.sh
Reading package lists...
Building dependency tree...
Reading state information...
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
npm is already the newest version (3.5.2-0ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
mkdir: cannot create directory ‘/home/ubuntu/projects’: File exists
--2017-05-16 22:56:58--  https://cdn4.iconfinder.com/data/icons/proglyphs-multimedia/512/Speaker-512.png
Resolving cdn4.iconfinder.com (cdn4.iconfinder.com)... 205.234.175.175
Connecting to cdn4.iconfinder.com (cdn4.iconfinder.com)|205.234.175.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23274 (23K) [image/png]
Saving to: ‘/home/ubuntu/projects/node/public/app/img/Speaker-512.png’

Speaker-512.png                    100%[=============================================================>]  22.73K  --.-KB/s    in 0.001s  

Last-modified header invalid -- time-stamp ignored.
2017-05-16 22:56:58 (27.2 MB/s) - ‘/home/ubuntu/projects/node/public/app/img/Speaker-512.png’ saved [23274/23274]

cp: cannot stat 'usr/local/bin/enable_web_startup': No such file or directory
chmod: cannot access '/usr/local/bin/enable_web_startup': No such file or directory
starter-node-angular@ /home/ubuntu/projects/node

2)
Would you like to have the WEB UI start every time ubuntu logs in?
Make Web UI available at each login? (y/n) :n
Web UI, will need to be started manually after each reboot, if you every change your mind please run the following command:
enable_web_startup
chmod: cannot access '/usr/local/bin/enable_web_startup': No such file or directory
It is suggested that you reboot your system at this time
Would you line to reboot now? (y/n) :n

**Comment by BaReinhard** [comment]
The file should be named enabled_web_startup

I must have either incorrectly named the file or referenced it incorrectly. You can manually move the files and everything should work.

**Comment by BaReinhard** [comment]
I correctly renamed the file for future installs thanks for bringing it to my attention. Simply move the file from the repo in the folder usr/local/bin/enabled_web_startup and move it to /usr/local/bin/enable_web_startup, then added permissions as an executable. Chmod +X /usr/local/bin/enable_web_startup

**Comment by BaReinhard** [comment]
This should have fixed the issue, if it did not please feel free to re open this issue. For the time being I will mark this as solved/closed
